Person.create!([
  {name: "landry manankoraisina", image: "landrymananko.jpg"},
  {name: "diego du crl", image: "diego_crl.jpg"},
  {name: "gens du crl", image: "crl.jpg"},
  {name: "lewis capaldi", image: "lc.jpeg"},
  {name: "harry styles", image: "hs.jpeg"},
  {name: "zakaria", image: "zakaria.jpeg"},
  {name: "ivan", image: "canope.jpeg"},
  {name: "virginie pape", image: "virginie_pape.jpg"},
  {name: "elise bertrand", image: "eb.jpeg"},
  {name: "meri", image: "m.jpg"},
  {name: "anna garde", image: "annagarde.jpeg"},
  {name: "anne sophie jourlin", image: "annesophie.jpg"},
  {name: "sofia plotnikova", image: "sofiap.jpeg"},
  {name: "krithika b", image: "krithikab.jpeg"},
  {name: "zoe pellegrin", image: "zp.jpg"},
  {name: "florence foresti", image: "fforest.jpeg"},
  {name: "nathan chan", image: "nchan.jpeg"},
  {name: "clara chan", image: "cchan.jpeg"},
  {name: "mona ber", image: "monab.jpeg"},
  {name: "audrey va", image: "AudreyVaring.jpeg"},
  {name: "pierre fabre", image: "pierrefl.jpg"},
  {name: "adoumie", image: "adoumie.jpg"},
  {name: "escarras", image: "adoumie1.jpg"},
  {name: "culture antique", image: "michalangelo.jpeg"},
  {name: "frau schubert", image: "voltaire.jpeg"},
  {name: "mme voisin", image: "pot-peinture-grec.jpeg"}
])
